env:
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
rules:
  indent:
    - warn
    - 4
  linebreak-style:
    - warn
    - unix
  no-unused-vars:
    - warn
  quotes:
    - warn
    - double
